"""on delete

Revision ID: f4b783360d03
Revises: c4280292af10
Create Date: 2020-06-05 12:44:23.631266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b783360d03'
down_revision = 'c4280292af10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_post_tags_id_fkey', 'tags_post', type_='foreignkey')
    op.create_foreign_key(None, 'tags_post', 'tags', ['tags_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_post', type_='foreignkey')
    op.create_foreign_key('tags_post_tags_id_fkey', 'tags_post', 'tags', ['tags_id'], ['id'])
    # ### end Alembic commands ###
